# Generated by Django 3.1.4 on 2020-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
    ]
